version: "3.4"

services:
  app:
    build:
      context: .
    container_name: budget
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      RAILS_ENV: production
      DATABASE_URL: postgres://budget:budget1234@172.18.0.3/budget